const bookmarkFolders = [
    { id: 10, userId: 1, name: "Favorites" },
    { id: 11, userId: 1, name: "Design" },
    { id: 12, userId: 2, name: "Tech" },
    { id: 13, userId: 2, name: "Memes" },
    { id: 14, userId: 1, name: "Work" },
    { id: 15, userId: 8, name: "Ideas" },
    { id: 16, userId: 2, name: "Memes" },
    { id: 17, userId: 4, name: "Favorites" },
    { id: 18, userId: 7, name: "Projects" },
    { id: 19, userId: 1, name: "Tech" },
    { id: 20, userId: 5, name: "Ideas" },
    { id: 21, userId: 6, name: "Inspiration" },
    { id: 22, userId: 13, name: "Favorites" },
    { id: 23, userId: 8, name: "Favorites" },
    { id: 24, userId: 7, name: "Design" },
    { id: 25, userId: 8, name: "Memes" },
    { id: 26, userId: 18, name: "Favorites" },
    { id: 27, userId: 18, name: "Work" },
    { id: 28, userId: 12, name: "Inspiration" },
    { id: 29, userId: 12, name: "Memes" },
    { id: 30, userId: 2, name: "Memes" },
    { id: 31, userId: 18, name: "Work" },
    { id: 32, userId: 10, name: "Tech" },
    { id: 33, userId: 8, name: "Ideas" },
    { id: 34, userId: 7, name: "Ideas" },
    { id: 35, userId: 13, name: "Inspiration" },
    { id: 36, userId: 18, name: "Memes" },
    { id: 37, userId: 19, name: "Memes" },
    { id: 38, userId: 3, name: "Tech" },
    { id: 39, userId: 4, name: "Work" }
  ];
  
  export default bookmarkFolders;  