const posts = [
  {
    id: "1",
    userId: 1,
    username: "MO Shawky",
    time: "10:45 AM",
    avatar: "https://example.com/profiles/mo.jpg",
    content: "Just launched a new UI kit 🔥 Check it out!",
    image: "https://picsum.photos/seed/1/600/400",
    comments: [
      {
        user: {
          name: "Brandi",
          avatar: "https://i.pravatar.cc/150?img=13",
        },
        time: "11:00 AM",
        text: "This is amazing 🔥",
      },
    ],
    likes: [
      { name: "Brandi", avatar: "https://i.pravatar.cc/150?img=13" },
      { name: "Lina Tran", avatar: "https://i.pravatar.cc/300?img=32" },
    ],
    likesCount: 2,
    reposts: [
      { name: "Ahmed Zaki", avatar: "https://i.pravatar.cc/300?img=27" },
    ],
    repostsCount: 1,
    bookmarks: [
      { name: "John Cena", avatar: "https://i.pravatar.cc/300?img=7" },
    ],
    bookmarksCount: 1,
  },
  {
    id: "2",
    userId: 2,
    username: "Jane Doe",
    time: "2:30 PM",
    avatar: "https://example.com/profiles/jane.jpg",
    content: "Check out my latest coding vlog.",
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
    comments: [
      {
        user: {
          name: "Brandi",
          avatar: "https://i.pravatar.cc/150?img=13",
        },
        time: "11:00 AM",
        text: "This is amazing 🔥",
      },
    ],
    likes: [
      { name: "Amira Said", avatar: "https://i.pravatar.cc/300?img=19" },
    ],
    likesCount: 1,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "3",
    userId: 3,
    username: "Alex Smith",
    time: "3:15 PM",
    avatar: "https://example.com/profiles/alex.jpg",
    content: "New blog post is up! 🚀",
    image: "https://picsum.photos/seed/2/600/400",
    likes: [],
    likesCount: 0,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "4",
    userId: 4,
    username: "Emily Jones",
    time: "4:45 PM",
    avatar: "https://example.com/profiles/emily.jpg",
    content: "Working on a React project!",
    video: "https://www.w3schools.com/html/movie.mp4",
    likes: [
      { name: "Techie Boy", avatar: "https://i.pravatar.cc/300?img=23" },
      { name: "Sara Dev", avatar: "https://i.pravatar.cc/300?img=29" },
    ],
    likesCount: 2,
    reposts: [
      { name: "CodeQueen", avatar: "https://i.pravatar.cc/300?img=35" },
    ],
    repostsCount: 1,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "5",
    userId: 5,
    username: "Michael Brown",
    time: "5:20 PM",
    avatar: "https://example.com/profiles/michael.jpg",
    content: "Photography vibes 📸",
    image: "https://picsum.photos/seed/3/600/400",
    likes: [
      { name: "Sara Dev", avatar: "https://i.pravatar.cc/300?img=29" },
    ],
    likesCount: 1,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "6",
    userId: 6,
    username: "Sophia Wilson",
    time: "6:10 PM",
    avatar: "https://example.com/profiles/sophia.jpg",
    content: "You can't see me! 🕶️",
    image: "https://picsum.photos/seed/4/600/400",
    likes: [],
    likesCount: 0,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "7",
    userId: 7,
    username: "Liam Miller",
    time: "7:00 PM",
    avatar: "https://example.com/profiles/liam.jpg",
    content: "Launching soon 🚀",
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
    likes: [
      { name: "Lina Tran", avatar: "https://i.pravatar.cc/300?img=32" },
      { name: "Brandi", avatar: "https://i.pravatar.cc/150?img=13" },
    ],
    likesCount: 2,
    reposts: [
      { name: "Ahmed Zaki", avatar: "https://i.pravatar.cc/300?img=27" },
    ],
    repostsCount: 1,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "8",
    userId: 8,
    username: "Olivia Davis",
    time: "8:30 PM",
    avatar: "https://example.com/profiles/olivia.jpg",
    content: "Debugging all day 😵‍💫",
    image: "https://picsum.photos/seed/5/600/400",
    likes: [],
    likesCount: 0,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "9",
    userId: 9,
    username: "Noah Garcia",
    time: "9:45 PM",
    avatar: "https://example.com/profiles/noah.jpg",
    content: "Responsive design tips 🧠",
    video: "https://www.w3schools.com/html/movie.mp4",
    likes: [],
    likesCount: 0,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "10",
    userId: 10,
    username: "Ava Martinez",
    time: "10:15 PM",
    avatar: "https://example.com/profiles/ava.jpg",
    content: "Frontend magic ✨",
    image: "https://picsum.photos/seed/6/600/400",
    likes: [],
    likesCount: 0,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "11",
    userId: 11,
    username: "William Rodriguez",
    time: "11:00 PM",
    avatar: "https://example.com/profiles/william.jpg",
    content: "Creating an innovative product! 🛠️",
    image: "https://picsum.photos/seed/7/600/400",
    likes: [
      { name: "Brandi", avatar: "https://i.pravatar.cc/150?img=13" },
    ],
    likesCount: 1,
    reposts: [
      { name: "John Cena", avatar: "https://i.pravatar.cc/300?img=7" },
    ],
    repostsCount: 1,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "12",
    userId: 12,
    username: "Mia Hernandez",
    time: "12:30 AM",
    avatar: "https://example.com/profiles/mia.jpg",
    content: "Life lessons learned through yoga 🙏",
    image: "https://picsum.photos/seed/8/600/400",
    likes: [],
    likesCount: 0,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "13",
    userId: 13,
    username: "James Moore",
    time: "1:00 AM",
    avatar: "https://example.com/profiles/james.jpg",
    content: "Excited about the future of tech 🚀",
    video: "https://www.w3schools.com/html/mov_bbb.mp4",
    likes: [],
    likesCount: 0,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "14",
    userId: 14,
    username: "Charlotte Taylor",
    time: "2:00 AM",
    avatar: "https://example.com/profiles/charlotte.jpg",
    content: "Environment conservation is crucial 🌱",
    image: "https://picsum.photos/seed/9/600/400",
    likes: [],
    likesCount: 0,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "15",
    userId: 15,
    username: "Jackson Lee",
    time: "3:00 AM",
    avatar: "https://example.com/profiles/jackson.jpg",
    content: "Building my first game! 🎮",
    image: "https://picsum.photos/seed/10/600/400",
    likes: [],
    likesCount: 0,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "16",
    userId: 16,
    username: "Lucas White",
    time: "4:00 AM",
    avatar: "https://example.com/profiles/lucas.jpg",
    content: "Python + Flask = 🔥",
    image: "https://picsum.photos/seed/11/600/400",
    likes: [],
    likesCount: 0,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "17",
    userId: 17,
    username: "Amelia Harris",
    time: "5:00 AM",
    avatar: "https://example.com/profiles/amelia.jpg",
    content: "Designing a new app interface 🖌️",
    video: "https://www.w3schools.com/html/movie.mp4",
    likes: [],
    likesCount: 0,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "18",
    userId: 18,
    username: "Ella Clark",
    time: "6:00 AM",
    avatar: "https://example.com/profiles/ella.jpg",
    content: "Brainstorming ideas for my next project 💡",
    image: "https://picsum.photos/seed/12/600/400",
    likes: [],
    likesCount: 0,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "19",
    userId: 19,
    username: "Benjamin Walker",
    time: "7:00 AM",
    avatar: "https://example.com/profiles/benjamin.jpg",
    content: "The future of AI is now! 🤖",
    image: "https://picsum.photos/seed/13/600/400",
    likes: [],
    likesCount: 0,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
  {
    id: "20",
    userId: 20,
    username: "Lily Adams",
    time: "8:00 AM",
    avatar: "https://example.com/profiles/lily.jpg",
    content: "Exploring the world of machine learning 🔍",
    image: "https://picsum.photos/seed/14/600/400",
    likes: [],
    likesCount: 0,
    reposts: [],
    repostsCount: 0,
    bookmarks: [],
    bookmarksCount: 0,
  },
];


export default posts;
