const usersAccounts = [
  {
    id: 1,
    email: 'mo@gmail.com',
    password: 'password123',
    name: 'SEIF AHMED',
    username: 'seifahmedb',
    profilePicture: 'https://i.pravatar.cc/150?img=1',
    bio: 'Passionate developer and footballer.',
    createdAt: '2025-04-28T10:00:00Z',
    isVerified: true,
    followers: [2, 5, 8, 10, 13, 15, 16, 19],
    following: [8, 10, 13, 14, 16, 17, 18],
    posts: [1],
  },
  {
    id: 2,
    email: 'jane.doe@example.com',
    password: 'password456',
    name: 'Jane Doe',
    username: 'jane_doe',
    profilePicture: 'https://i.pravatar.cc/150?img=1',
    bio: 'Traveler and photographer.',
    createdAt: '2025-04-26T15:30:00Z',
    isVerified: false,
    followers: [8, 20],
    following: [1, 4, 5, 6, 7, 12, 13, 14, 17],
    posts: [2],
  },
  {
    id: 3,
    email: 'alex.smith@example.com',
    password: 'alexPass789',
    name: 'Alex Smith',
    username: 'alex_smith',
    profilePicture: 'https://i.pravatar.cc/150?img=1',
    bio: 'Tech enthusiast and blogger.',
    createdAt: '2025-04-20T12:00:00Z',
    isVerified: true,
    followers: [5, 9, 11, 14, 16, 18, 20],
    following: [9, 11, 12, 13, 15, 17],
    posts: [3, 6],
  },
  {
    id: 4,
    email: 'emily.jones@example.com',
    password: 'emilySecure456',
    name: 'Emily Jones',
    username: 'emily_jones',
    profilePicture: 'https://i.pravatar.cc/150?img=1',
    bio: 'Loves art and digital painting.',
    createdAt: '2025-04-18T14:15:00Z',
    isVerified: false,
    followers: [5, 6, 8],
    following: [1, 9, 10, 14, 15],
    posts: [4],
  },
  {
    id: 5,
    email: 'michael.brown@example.com',
    password: 'michaelPass321',
    name: 'Michael Brown',
    username: 'michael_brown',
    profilePicture: 'https://i.pravatar.cc/150?img=1',
    bio: 'Fitness freak and gym trainer.',
    createdAt: '2025-04-17T10:30:00Z',
    isVerified: true,
    followers: [2, 3, 8, 11, 12],
    following: [1, 4, 5, 7, 16],
    posts: [7, 8],
  },
  {
    id: 6,
    email: 'sophia.wilson@example.com',
    password: 'sophiaLove321',
    name: 'Sophia Wilson',
    username: 'sophia_wilson',
    profilePicture: 'https://i.pravatar.cc/150?img=1',
    bio: 'Fashion designer and stylist.',
    createdAt: '2025-04-16T09:20:00Z',
    isVerified: false,
    followers: [1, 5, 7, 9, 14],
    following: [3, 4],
    posts: [9],
  },
  {
    id: 7,
    email: 'liam.miller@example.com',
    password: 'liamBest123',
    name: 'Liam Miller',
    username: 'liam_miller',
    profilePicture: 'https://i.pravatar.cc/150?img=1',
    bio: 'Gamer and streamer.',
    createdAt: '2025-04-15T08:45:00Z',
    isVerified: true,
    followers: [1, 8, 12],
    following: [2, 5, 6],
    posts: [10, 11],
  },
  {
    id: 8,
    email: 'olivia.davis@example.com',
    password: 'oliviaStar456',
    name: 'Olivia Davis',
    username: 'olivia_davis',
    profilePicture: 'https://example.com/profiles/olivia.jpg',
    bio: 'Writer and poet.',
    createdAt: '2025-04-14T11:00:00Z',
    isVerified: true,
    followers: [7, 12, 13],
    following: [9, 10],
    posts: [12],
  },
  {
    id: 9,
    email: 'noah.garcia@example.com',
    password: 'noahSecure789',
    name: 'Noah Garcia',
    username: 'noah_garcia',
    profilePicture: 'https://example.com/profiles/noah.jpg',
    bio: 'Chef and food critic.',
    createdAt: '2025-04-13T07:30:00Z',
    isVerified: false,
    followers: [8, 11],
    following: [10, 11, 12],
    posts: [13],
  },
  {
    id: 10,
    email: 'ava.martinez@example.com',
    password: 'avaPass321',
    name: 'Ava Martinez',
    username: 'ava_martinez',
    profilePicture: 'https://example.com/profiles/ava.jpg',
    bio: 'Photographer and adventurer.',
    createdAt: '2025-04-12T06:50:00Z',
    isVerified: true,
    followers: [8, 9, 14],
    following: [11, 12],
    posts: [14],
  },
  {
    id: 11,
    email: 'william.rodriguez@example.com',
    password: 'willSecure123',
    name: 'William Rodriguez',
    username: 'william_rodriguez',
    profilePicture: 'https://example.com/profiles/william.jpg',
    bio: 'Soccer coach and mentor.',
    createdAt: '2025-04-11T15:00:00Z',
    isVerified: false,
    followers: [9, 10],
    following: [12, 13],
    posts: [15],
  },
  {
    id: 12,
    email: 'mia.hernandez@example.com',
    password: 'miaLove456',
    name: 'Mia Hernandez',
    username: 'mia_hernandez',
    profilePicture: 'https://example.com/profiles/mia.jpg',
    bio: 'Yoga instructor and wellness coach.',
    createdAt: '2025-04-10T13:10:00Z',
    isVerified: true,
    followers: [10, 11],
    following: [13, 14],
    posts: [16],
  },
  {
    id: 13,
    email: 'james.moore@example.com',
    password: 'jamesSecure789',
    name: 'James Moore',
    username: 'james_moore',
    profilePicture: 'https://example.com/profiles/james.jpg',
    bio: 'Entrepreneur and investor.',
    createdAt: '2025-04-09T12:30:00Z',
    isVerified: true,
    followers: [11, 12],
    following: [14, 15],
    posts: [17],
  },
  {
    id: 14,
    email: 'charlotte.taylor@example.com',
    password: 'charlottePass321',
    name: 'Charlotte Taylor',
    username: 'charlotte_taylor',
    profilePicture: 'https://example.com/profiles/charlotte.jpg',
    bio: 'Environmentalist and nature lover.',
    createdAt: '2025-04-08T10:20:00Z',
    isVerified: false,
    followers: [12, 13],
    following: [15, 16],
    posts: [18],
  },
  {
    id: 15,
    email: 'benjamin.anderson@example.com',
    password: 'benjaminBest123',
    name: 'Benjamin Anderson',
    username: 'benjamin_anderson',
    profilePicture: 'https://example.com/profiles/benjamin.jpg',
    bio: 'Film director and critic.',
    createdAt: '2025-04-07T09:45:00Z',
    isVerified: true,
    followers: [13, 14],
    following: [16, 17],
    posts: [19],
  },
  {
    id: 16,
    email: 'amelia.thomas@example.com',
    password: 'ameliaSecure456',
    name: 'Amelia Thomas',
    username: 'amelia_thomas',
    profilePicture: 'https://example.com/profiles/amelia.jpg',
    bio: 'Painter and sculptor.',
    createdAt: '2025-04-06T08:15:00Z',
    isVerified: true,
    followers: [14, 15],
    following: [17, 18],
    posts: [20],
  },
  {
    id: 17,
    email: 'lucas.jackson@example.com',
    password: 'lucasPass789',
    name: 'Lucas Jackson',
    username: 'lucas_jackson',
    profilePicture: 'https://example.com/profiles/lucas.jpg',
    bio: 'Mountain climber and adventurer.',
    createdAt: '2025-04-05T07:40:00Z',
    isVerified: false,
    followers: [15, 16],
    following: [18, 19],
    posts: [],
  },
  {
    id: 18,
    email: 'harper.white@example.com',
    password: 'harperSecure321',
    name: 'Harper White',
    username: 'harper_white',
    profilePicture: 'https://example.com/profiles/harper.jpg',
    bio: 'Animal rights activist.',
    createdAt: '2025-04-04T06:20:00Z',
    isVerified: true,
    followers: [16, 17],
    following: [19, 20],
    posts: [],
  },
  {
    id: 19,
    email: 'ethan.harris@example.com',
    password: 'ethanBest456',
    name: 'Ethan Harris',
    username: 'ethan_harris',
    profilePicture: 'https://example.com/profiles/ethan.jpg',
    bio: 'Space enthusiast and astronomer.',
    createdAt: '2025-04-03T05:55:00Z',
    isVerified: true,
    followers: [17, 18],
    following: [20],
    posts: [],
  },
  {
    id: 20,
    email: 'abigail.clark@example.com',
    password: 'abigailSecure789',
    name: 'Abigail Clark',
    username: 'abigail_clark',
    profilePicture: 'https://example.com/profiles/abigail.jpg',
    bio: 'Tech reviewer and podcaster.',
    createdAt: '2025-04-02T04:40:00Z',
    isVerified: false,
    followers: [18, 19],
    following: [],
    posts: [],
  },
];

export default usersAccounts;
